openapi: 3.0.0
x-nhs-api-spec-guid: c488b99d-f9df-481b-a903-f16cab4855a6
x-meta:
  service_name: "fhir-converter"
  short_service_name: "fc"
  product_display_name: "FHIR Converter"
  service_base_path: "fhir-converter"
  product_description: "This proxy function as a converter from FHIR R4 to STU3 and vice versa"
  pipeline_name_prefix: "FHIR-Converter"
info:
  version: "{VERSION}"
  title: FHIR Converter
  description: |
    ## Overview
    This proxy function as a converter from FHIR R4 to STU3 and vice versa
  contact:
    name: FHIR Converter
    url: "https://digital.nhs.uk/developer/help-and-support"
    email: api.management@nhs.net
servers:
  - url: "https://sandbox.api.service.nhs.uk/fhir-converter"
    description: Sandbox environment.
  - url: "https://int.api.service.nhs.uk/fhir-converter"
    description: Integration test environment.
  - url: "https://api.service.nhs.uk/fhir-converter"
    description: "Production environment."
tags:
  - name: FHIR Converter
paths:
  /convert:
    post:
      summary: Convert FHIR payload
      operationId: convert
      requestBody:
        content:
          "application/fhir+json; fhirVersion=3.0":
            examples:
              MedicationRequest:
                $ref: "#/components/examples/MedicationRequest_STU3_JSON"
              MedicationStatement:
                $ref: "#/components/examples/MedicationStatement_STU3_JSON"
          "application/fhir+xml; fhirVersion=3.0":
            examples:
              MedicationRequest:
                $ref: "#/components/examples/MedicationRequest_STU3_XML"
              MedicationStatement:
                $ref: "#/components/examples/MedicationStatement_STU3_XML"
          "application/fhir+json; fhirVersion=4.0":
            examples:
              MedicationRequest:
                $ref: "#/components/examples/MedicationRequest_R4_JSON"
              MedicationStatement:
                $ref: "#/components/examples/MedicationStatement_R4_JSON"
          "application/fhir+xml; fhirVersion=4.0":
            examples:
              MedicationRequest:
                $ref: "#/components/examples/MedicationRequest_R4_XML"
              MedicationStatement:
                $ref: "#/components/examples/MedicationStatement_R4_XML"
      responses:
        "200":
          description: Successful convertion
          content:
            "application/fhir+json; fhirVersion=3.0":
              examples:
                MedicationRequest:
                  $ref: "#/components/examples/MedicationRequest_STU3_JSON"
                MedicationStatement:
                  $ref: "#/components/examples/MedicationStatement_STU3_JSON"
            "application/fhir+xml; fhirVersion=3.0":
              examples:
                MedicationRequest:
                  $ref: "#/components/examples/MedicationRequest_STU3_XML"
                MedicationStatement:
                  $ref: "#/components/examples/MedicationStatement_STU3_XML"
            "application/fhir+json; fhirVersion=4.0":
              examples:
                MedicationRequest:
                  $ref: "#/components/examples/MedicationRequest_R4_JSON"
                MedicationStatement:
                  $ref: "#/components/examples/MedicationStatement_R4_JSON"
            "application/fhir+xml; fhirVersion=4.0":
              examples:
                MedicationRequest:
                  $ref: "#/components/examples/MedicationRequest_R4_XML"
                MedicationStatement:
                  $ref: "#/components/examples/MedicationStatement_R4_XML"
        "400":
          description: Invalid request
          content:
            "application/fhir+json; fhirVersion=4.0":
              examples:
                "Invalid or missing header":
                  $ref: "#/components/examples/InvalidOrMissingHeader"

components:
  examples:
    "MedicationRequest_R4_JSON":
      summary: R4 JSON MedicationRequest
      value:
        $ref: "components/examples/MedicationRequest/r4.json"
    "MedicationStatement_R4_JSON":
      summary: R4 JSON MedicationStatement
      value:
        $ref: "components/examples/MedicationStatement/r4.json"
    "MedicationRequest_R4_XML":
      summary: R4 XML MedicationRequest
      value:
        $ref: "components/examples/MedicationRequest/r4.xml"
    "MedicationStatement_R4_XML":
      summary: R4 XML MedicationStatement
      value:
        $ref: "components/examples/MedicationStatement/r4.xml"
    "MedicationRequest_STU3_JSON":
      summary: STU3 JSON MedicationRequest
      value:
        $ref: "components/examples/MedicationRequest/stu3.json"
    "MedicationStatement_STU3_JSON":
      summary: STU3 JSON MedicationStatement
      value:
        $ref: "components/examples/MedicationStatement/stu3.json"
    "MedicationRequest_STU3_XML":
      summary: STU3 XML MedicationRequest
      value:
        $ref: "components/examples/MedicationRequest/stu3.xml"
    "MedicationStatement_STU3_XML":
      summary: STU3 XML MedicationStatement
      value:
        $ref: "components/examples/MedicationStatement/stu3.xml"
    "InvalidOrMissingHeader":
      summary: Invalid of missing header errror
      value:
        $ref: "components/examples/400.json"
